ATTACHMENTS_FOLDER = "./attachments"
TMP_FOLDER = ATTACHMENTS_FOLDER + "/tmp"
DOCS_FOLDER = ATTACHMENTS_FOLDER + "/docs"
EXCEL_FOLDER = ATTACHMENTS_FOLDER + "/excel"
EXCEL_WORKBOOK = EXCEL_FOLDER + "/table.xlsx"

IMAGES_FOLDER_NAME = "images"
IMAGES_FOLDER = f"{ATTACHMENTS_FOLDER}/{IMAGES_FOLDER_NAME}"

PASSWORD_FILE = "pass.txt"

IMG_PROPERTY = "foto"
