ATTACHMENTS_FOLDER = './attachments'
DOCS_FOLDER = ATTACHMENTS_FOLDER + '/docs'
EXCEL_FOLDER = ATTACHMENTS_FOLDER + '/excel'

IMAGES_FOLDER_NAME = 'images'
IMAGES_FOLDER = f"{ATTACHMENTS_FOLDER}/{IMAGES_FOLDER_NAME}"

IMG_PROPERTY = 'foto'